version: "3.6"

services:
 db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_USER=db_user
      - POSTGRES_DB=db_db
 web:
    build:
     context: .
     dockerfile: Dockerfile
    command: gunicorn PyEditorial.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/code
    expose:
      - 8000
    depends_on:
      - db

 nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

volumes:
  postgres_data:
